/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "my_lib.h"

#define PORT10_BASE     (0xF003B000)
#define PORT10_IOCR0    (*(volatile unsigned int*)(PORT10_BASE + 0x10))
#define PORT10_OMR      (*(volatile unsigned int*)(PORT10_BASE + 0x04))

#define PC1             11
#define PC2             19

#define PCL1            17
#define PCL2            18
#define PS1             1
#define PS2             2

/* Define PORT02 Registers for Switch2 */
#define PORT02_BASE     (0xF003A200)
#define PORT02_IOCR0    (*(volatile unsigned int*)(PORT02_BASE + 0x10))
#define PORT02_IN       (*(volatile unsigned int*)(PORT02_BASE + 0x24))


#define PC1             11
#define P1              1
#define PC0             3
#define P0              0
#define P2              2

#define SYSTEM_TIMER_0_31_0 *(volatile unsigned int *)(0xF0000000+0x10)
#define DELAY_250MS (5000000 * 25 / 30)

volatile unsigned int SW1_curr;
volatile unsigned int SW1_prev;
volatile unsigned int SW1_cnt;
volatile unsigned int SW1_debounce;

volatile unsigned int SW2_curr;
volatile unsigned int SW2_prev;
volatile unsigned int SW2_cnt;
volatile unsigned int SW2_debounce;

volatile unsigned int SW_state_curr;
volatile unsigned int SW_state_prev;
volatile unsigned int SW_state_cnt;
volatile unsigned int SW_state_debounce;

volatile unsigned char irq_timer;
volatile unsigned int count_index;

IfxCpu_syncEvent g_cpuSyncEvent = 0;

/* Initialize LED (RED & BLUE) */
/*void init_LED(void)
{
     Reset PC1 & PC2 in IOCR0
    PORT10_IOCR0 &= ~((0x1F) << PC1);
    PORT10_IOCR0 &= ~((0x1F) << PC2);

     Set PC1 & PC2 with push-pull(2b10000)
    PORT10_IOCR0 |= ((0x10) << PC1);
    PORT10_IOCR0 |= ((0x10) << PC2);
}*/

/* Initialize Switch2
void init_Switch(void)
{
     Reset PC1 in IOCR0
    PORT02_IOCR0 &= ~((0x1F) << PC1);

     Set PC1 with push-up(5b0xx10) 000010
    PORT02_IOCR0 |= ((0x2) << PC1);

     Reset PC2 in IOCR0
    PORT02_IOCR0 &= ~((0x1F) << PC2);

    Set PC2 with push-up(5b0xx10)
   PORT02_IOCR0 |= ((0x2) << PC2); //**
}*/

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    volatile int cycle;
    volatile int system_tick;

    init_LED();
    count_index =1;
    SW1_curr = 0;
    SW1_prev = 0;
    SW1_cnt = 0;
    SW1_debounce = 0;
    SW2_curr = 0;
    SW2_prev = 0;
    SW2_cnt = 0;
    SW2_debounce = 0;
    SW_state_curr = 0;
    SW_state_prev = 0;
    SW_state_cnt = 0;
    SW_state_debounce = 0;

    irq_timer = 0;

    // CCU61 T12 100ms
    init_CCU6((myCCU6 *)&CCU61,100,0x0F);

    while(1)
    {

        // 100ms
       irq_timer = 0;
       while( irq_timer == 0 );

       // FIXME: state debounce
       SW_state_prev = SW_state_curr;
       SW_state_curr = (SW2_debounce<<1) | (SW1_debounce<<0);

       if( SW_state_curr != SW_state_prev )
           SW_state_cnt = 0;
       else if( SW_state_cnt < 10 )
           SW_state_cnt ++;
       else
           SW_state_debounce = SW_state_curr;


       if( SW_state_debounce != 0 && SW_state_debounce == 0x03)
       {
          while(1)
           {
               PORT10_OMR |= ((1<<PS1) | (1<<PS2));           // Toggle LED RED AND BLUE

               for(cycle = 0; cycle < DELAY_250MS ; cycle++); // Delay

               PORT10_OMR |= ((1<<PCL2) | (1<<PCL1));

               for(cycle = 0; cycle < DELAY_250MS ; cycle++); // Delay


           }
       }
    }
   return (1);
}


// 100ms timer
__interrupt( 0x0F ) __vector_table( 0 )
void CCU61_T12_ISR(void)
{
    SW1_prev = SW1_curr;
    SW1_curr = (PORT02_IN & (1<<P0)) == 0;
    SW2_prev = SW2_curr;
    SW2_curr = (PORT02_IN & (1<<P1)) == 0;

    // FIXME: SW1, SW2 software debounce for 1 second
    if( SW1_curr != SW1_prev )
        SW1_cnt = 0;
    else if( SW1_cnt < 9 )
        SW1_cnt ++;
    else
        SW1_debounce = SW1_curr;

    if( SW2_curr != SW2_prev )
        SW2_cnt = 0;
    else if( SW1_cnt < 9 )
        SW2_cnt ++;
    else
        {
        SW2_debounce = SW2_curr;
        ++count_index;
        }




    irq_timer = 1;
}
